# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170126_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='treasure_images/default.png', upload_to='treasure_images'),
        ),
    ]
