# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_treasure_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
